apiVersion: v2
name: loki
description: Loki log aggregation system
type: application
version: 1.0.0

dependencies:
  - name: loki
    version: "6.6.2"
    repository: https://grafana.github.io/helm-charts
