apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: storage-class
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-2"  # Install before everything else
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/drpowell23-del/capstone_project.git
    targetRevision: HEAD
    path: apps/storage-class
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
