apiVersion: v2
name: tempo
description: Tempo tracing backend
type: application
version: 1.0.0

dependencies:
  - name: tempo
    version: "1.10.3"
    repository: https://grafana.github.io/helm-charts
